export { default as FAQ } from './FAQ/FAQ'
export { default as HomeMerit } from './HomeMerit/HomeMerit'
export { default as Merit } from './Merit/Merit'
export { default as OurStory } from './OurStory/OurStory'
export { default as Promotion } from './Promotion/Promotion'
export { default as Download } from './Download/Download'
export { default as HomeFAQ } from './HomeFAQ/HomeFAQ'
export { default as LoginForm } from './LoginForm/LoginForm'
