export { default as Home } from './Home/Home'
export { default as LogIn } from './LogIn/LogIn'
export { default as SignUp } from './SignUp/SignUp'
export { default as Browse } from './Browse/Browse'
export { default as Profile } from './Profile/Profile'
export { default as PageNotFound } from './PageNotFound/PageNotFound'
